// GENERATED by islands/migrate.mjs — do not edit by hand.
// Maps demoId -> demo component. Bundled self-contained (own React copy)
// into public/preview-islands/islands.js by islands/build.mjs.
import type { JSX } from 'react'
import { createRoot } from 'react-dom/client'
import { ButtonDemo } from '../content/docs/components/actions/_button-demo'
import { ButtonGroupDemo } from '../content/docs/components/actions/_button-group-demo'
import { IconButtonDemo } from '../content/docs/components/actions/_icon-button-demo'
import { LinkDemo } from '../content/docs/components/actions/_link-demo'
import { PaginationDemo } from '../content/docs/components/data/_pagination-demo'
import { TableDemo } from '../content/docs/components/data/_table-demo'
import { DialogDemo } from '../content/docs/components/feedback/_dialog-demo'
import { DrawerDemo } from '../content/docs/components/feedback/_drawer-demo'
import { MessageDemo } from '../content/docs/components/feedback/_message-demo'
import { PopoverDemo } from '../content/docs/components/feedback/_popover-demo'
import { ProgressDemo } from '../content/docs/components/feedback/_progress-demo'
import { SpinnerDemo } from '../content/docs/components/feedback/_spinner-demo'
import { ToastDemo } from '../content/docs/components/feedback/_toast-demo'
import { TooltipDemo } from '../content/docs/components/feedback/_tooltip-demo'
import { CheckboxDemo } from '../content/docs/components/form/_checkbox-demo'
import { CheckboxGroupDemo } from '../content/docs/components/form/_checkbox-group-demo'
import { ComboboxDemo } from '../content/docs/components/form/_combobox-demo'
import { FieldDemo } from '../content/docs/components/form/_field-demo'
import { InputDemo } from '../content/docs/components/form/_input-demo'
import { InputGroupDemo } from '../content/docs/components/form/_input-group-demo'
import { NumberInputDemo } from '../content/docs/components/form/_number-input-demo'
import { RadioDemo } from '../content/docs/components/form/_radio-demo'
import { RadioGroupDemo } from '../content/docs/components/form/_radio-group-demo'
import { SelectDemo } from '../content/docs/components/form/_select-demo'
import { SliderDemo } from '../content/docs/components/form/_slider-demo'
import { SwitchDemo } from '../content/docs/components/form/_switch-demo'
import { TextareaDemo } from '../content/docs/components/form/_textarea-demo'
import { ContainerDemo } from '../content/docs/components/layout/_container-demo'
import { GridDemo } from '../content/docs/components/layout/_grid-demo'
import { StackDemo } from '../content/docs/components/layout/_stack-demo'
import { AccordionDemo } from '../content/docs/components/navigation/_accordion-demo'
import { BreadcrumbDemo } from '../content/docs/components/navigation/_breadcrumb-demo'
import { MenuDemo } from '../content/docs/components/navigation/_menu-demo'
import { TabsDemo } from '../content/docs/components/navigation/_tabs-demo'
import { AvatarDemo } from '../content/docs/components/surfaces/_avatar-demo'
import { CardDemo } from '../content/docs/components/surfaces/_card-demo'
import { BadgeDemo } from '../content/docs/components/typography/_badge-demo'
import { DividerDemo } from '../content/docs/components/typography/_divider-demo'
import { HeadingDemo } from '../content/docs/components/typography/_heading-demo'
import { KbdDemo } from '../content/docs/components/typography/_kbd-demo'
import { SkeletonDemo } from '../content/docs/components/typography/_skeleton-demo'
import { TextDemo } from '../content/docs/components/typography/_text-demo'

const registry: Record<string, () => JSX.Element> = {
  'components/actions/button': ButtonDemo,
  'components/actions/button-group': ButtonGroupDemo,
  'components/actions/icon-button': IconButtonDemo,
  'components/actions/link': LinkDemo,
  'components/data/pagination': PaginationDemo,
  'components/data/table': TableDemo,
  'components/feedback/dialog': DialogDemo,
  'components/feedback/drawer': DrawerDemo,
  'components/feedback/message': MessageDemo,
  'components/feedback/popover': PopoverDemo,
  'components/feedback/progress': ProgressDemo,
  'components/feedback/spinner': SpinnerDemo,
  'components/feedback/toast': ToastDemo,
  'components/feedback/tooltip': TooltipDemo,
  'components/form/checkbox': CheckboxDemo,
  'components/form/checkbox-group': CheckboxGroupDemo,
  'components/form/combobox': ComboboxDemo,
  'components/form/field': FieldDemo,
  'components/form/input': InputDemo,
  'components/form/input-group': InputGroupDemo,
  'components/form/number-input': NumberInputDemo,
  'components/form/radio': RadioDemo,
  'components/form/radio-group': RadioGroupDemo,
  'components/form/select': SelectDemo,
  'components/form/slider': SliderDemo,
  'components/form/switch': SwitchDemo,
  'components/form/textarea': TextareaDemo,
  'components/layout/container': ContainerDemo,
  'components/layout/grid': GridDemo,
  'components/layout/stack': StackDemo,
  'components/navigation/accordion': AccordionDemo,
  'components/navigation/breadcrumb': BreadcrumbDemo,
  'components/navigation/menu': MenuDemo,
  'components/navigation/tabs': TabsDemo,
  'components/surfaces/avatar': AvatarDemo,
  'components/surfaces/card': CardDemo,
  'components/typography/badge': BadgeDemo,
  'components/typography/divider': DividerDemo,
  'components/typography/heading': HeadingDemo,
  'components/typography/kbd': KbdDemo,
  'components/typography/skeleton': SkeletonDemo,
  'components/typography/text': TextDemo,
}

export function mount(demoId: string, container: Element): () => void {
  const Demo = registry[demoId]
  if (!Demo) {
    throw new Error(`Unknown preview island: ${demoId}`)
  }
  const root = createRoot(container)
  root.render(<Demo />)
  return () => {
    root.unmount()
  }
}
